cylbot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers
  head_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_pan
    pid: {p: 1.0, i: 0.01, d: 1.0}
  head_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_tilt
    pid: {p: 400.0, i: 1.0, d: 10.0}